language: node_js
node_js:
- 8
before_script:
- "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
- "chmod +x ./cc-test-reporter"
- "./cc-test-reporter before-build"
deploy:
  provider: npm
  email: ci@bowtie.co
  skip_cleanup: true
  on:
    tags: true
    repo: bowtie-co/node-api
  api_key:
    secure: KcLORDeofVlk1GQXHbpG0tm2Civ6sLk06e4o92PWVn0D9pMnvCKbiTtWd7h9RomIXHBFsqrF/yth1MAncaBZnnWJ0NDvuMbLuR1voZp+q/7L2gwMV3Wdarek6Eb0kseE+J6VDoAhTxYBAXpHrR5pNIF8cnBlvQrTS9eeaC6CkpX8izBhkY4AwOIqXGwjerzhZ+BJ9qPJUtlAOvo7w/EJoeUGa/htQ8Hy28ABpDXfSzR447bPWlHx9LjG11PGtOdFSgRKm0R0o+xKJGC8TH1CEXcaxw7nQUNzlLnBQcOsNQNPK/FvJcWriBuKJvhKYwXAlTDjRI+9Ym1MTHyT8s4QvKVALWmEc7jrkobW72n34IzEdjcd3wjsA44UlX5RCIdvz7DIRvInzBUN/0KEClTDC2uilpfNcw8tcUFCaTTZNmoxIbFrGFK1BLTkS6GIPRzdP7fhQQzv1hzJrWls3KICjn2HVnfBp62F6QnwMKDGwScsecnVtX2lRXF6hHJUjkZJ092bb0qVV7P5YU5ZHgnl4As6dMEzaszhqE7J39A+DvHUPMaqYFXFsCKM0PfQdTJQKcd7j1BmXJyFaIKAnIE9IGyQyyxmmxez7ve/kOrnFfKF+q1glJ6cHzBiEZ/y6x5BiMMBt/MJRCggpoZ/t/DYmHT+D4VGTNYQCZzVRvaMVrM=
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
  slack:
    secure: R3s4/Hn7IYYwiR6fd0BKDtEDrtt8hBzf6LdbrhCY/xHvBorcUaM7j/acOCAMge1sig3O91WVSNk3/lUrKvYAyUcgfPTbMj/W74y0M92+PBNKDUA8FHQXyzuwsiyWDdAUtl4JbJRFoZZuAnTLD9+1hqyXZjbq35wJ09BWAAHDcCgtXrhksIG0wh3JISLgjG8qsntGrHlYTTjoedA5rzG0rczMdW6Veu5lbQYBhA9WBeLXgu3fKyjCT/PjUITLOjqbDC6mpVgf3z1jRUWrKPjQbGI+f39yIuAIhmO3BkxTMpbWUqnGsLVsez4M9NVWlVWz4xFP28lXI/7orVM6K7fyAicEvpuIT6DTFysvpEPq4dgg7cSF6k0o+Tkjs1pYKdv6Ge2T6vjTC35PLJDA5w+z0AdJZFBL3EV/XUryqtoTjBYJVwxnRiQxNhUiIgCIwCKcwY7EGK7uPJZmTRjmen/bBwJ4KzQnE2UI4K/H029lQxKVfFDlQ1toCNjEe/p71kOpKZyT8bepo25othoZjnrAyNAKAV59nryACEVEnP00YlSGe+gQemX7JXPZKQXzfLOezgCSxQUgNDloQoqha9eyBiICM0LMbc4doVTRQxIJgw5KevHLyaQMfH9GZBpXg39oFG/lw/3oaLVRvwvtuTq2Air0Ey7OcVG/Ab98S6/o2qo=
env:
  global:
    secure: oByP4oqXpANiO2a1PUKXZsVyZE5XkIQi6pu6/iWx7gfwkHcwSZmIp+HcWb/vz6pzUN/SUoyx1KaFrWd321sEzzpLulKKIng0x6/AauAnXbEh6n52trFmpIwIeS9NYYLYGgY3v1Xrso+cXMOMOd84jxD4tNrdM0hoAwe3+CqN6qE+B31xvOBkLSAX4Rq5g//HI2DxNv6VWV7HzzPkzULhJdp6uDsAeUXngpzJH5g2EwB8yRwkWDa0f2j8lERFgHd0WpJ03r85up6LTLgJ4zpAgfoscTOPb+bPwC/TqCE76gP7tGrVqNu4AEMMuDY4c0hw2QVS5uXT3yAZkhbVT60CseQOXqMJX871SFYpgg5/Lf4mOLj+VVzQ7QJbhWXYSS9PDorc0EODcGNLGdHTwMobxILubXCge3+v1F63/onaObxdEYPH0gypEFZdghWoyUgKp6VBd6ariLe5OOb6pP3XjrjQCBazQC9TQg4yMxpOQ2/ECpiDUMOxUvcTjlsPTgc4d260qc5rWRujDyo5VqsuwjvmexDh9H6ubgvWfEWHpJ4vwPCcnSpW350fI+TBmrkm1twSnymi0kc4mG+ZebWSvMGAeRqBAsUf/JW3UDqV/Bpc6ZhzuAaRsZS4/QDWhqJ8iGeYCaKubfm1Gb5g7Ln8ItwhwFZuYq1DWVw0An1BhXI=
