language: node_js
node_js:
- 8
deploy:
  provider: npm
  email: charlie@bowtie.co
  skip_cleanup: true
  on:
    tags: true
    repo: bowtie-co/node-api
  api_key:
    secure: k1MooLA9plSBkIflxoprni1c0DPgxUZqzkZht/AkKT4CjGUTN/TiQ5F6N5tuAlpa0U23bjL4QGUxdkaQE9xT/c9g74wf4GLCzT1TthPueDyAQ7q9NDLlIeIN1SZsW9j8Nha8N75BLu2vMJdj8DBt9LT8jqwgEaiP0AjshE/OM6SyBItrc9Y0T13wlrTlAI8DmBwfqiEbhGlsP0rZ0lL1u/AAscM8z/NphsfRr0koS/ED4q2Vclx+gH5s3vb/MsyRX6XGE5hwPsuiLGV39tYVTTblVrMoKKISQciy7ucS9V+xLqtjNTuZF7DKVaOY3+RnmHn2PNA2161u1yD1Z69f4dXAUo95uA1J1qLlfWj1RGiItIds0dLtyE+4O8ylT4Tqk+j62POmYuGY3YoyMNuJHvoQj+5KzgWvs7f/Uu8Is5rRz6jsWZ8IX230wt7j3us7cUkHlhwS9D4TnBFcYBNHNNpjagk6b1GVPCPb2qJ6vd8qB1NBBUxJgkYlFkt1UicmMd2DURpsJJ7Ai1iMkl617fMlx9xu/JydaCuCxtP0PhWrv1aTRRAb8QXKnVAFIFwHL0saNni9hLlwMVJSYkPbgDXaXiuqG478g3UsHJPuZmOAtb54NxoJayMHyK4lToWmDWYIRYgQ9EDqMrGgzGvY3Es6jRlpbFVG5C+64hdg3nY=
notifications:
  slack:
    secure: R3s4/Hn7IYYwiR6fd0BKDtEDrtt8hBzf6LdbrhCY/xHvBorcUaM7j/acOCAMge1sig3O91WVSNk3/lUrKvYAyUcgfPTbMj/W74y0M92+PBNKDUA8FHQXyzuwsiyWDdAUtl4JbJRFoZZuAnTLD9+1hqyXZjbq35wJ09BWAAHDcCgtXrhksIG0wh3JISLgjG8qsntGrHlYTTjoedA5rzG0rczMdW6Veu5lbQYBhA9WBeLXgu3fKyjCT/PjUITLOjqbDC6mpVgf3z1jRUWrKPjQbGI+f39yIuAIhmO3BkxTMpbWUqnGsLVsez4M9NVWlVWz4xFP28lXI/7orVM6K7fyAicEvpuIT6DTFysvpEPq4dgg7cSF6k0o+Tkjs1pYKdv6Ge2T6vjTC35PLJDA5w+z0AdJZFBL3EV/XUryqtoTjBYJVwxnRiQxNhUiIgCIwCKcwY7EGK7uPJZmTRjmen/bBwJ4KzQnE2UI4K/H029lQxKVfFDlQ1toCNjEe/p71kOpKZyT8bepo25othoZjnrAyNAKAV59nryACEVEnP00YlSGe+gQemX7JXPZKQXzfLOezgCSxQUgNDloQoqha9eyBiICM0LMbc4doVTRQxIJgw5KevHLyaQMfH9GZBpXg39oFG/lw/3oaLVRvwvtuTq2Air0Ey7OcVG/Ab98S6/o2qo=
